modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory
logoFile="scLogo.png"
license="GNU GPL v3.0 https://github.com/Geforce132/SecurityCraft/blob/1.17.1/LICENSE"
issueTrackerURL="http://github.com/Geforce132/SecurityCraft/issues"

[[mods]] #mandatory
	modId="securitycraft" #mandatory
	version="${file.jarVersion}" #mandatory
	displayName="SecurityCraft" #mandatory
	updateJSONURL="https://www.github.com/Geforce132/SecurityCraft/raw/master/Updates/Forge.json"
	description='''Adds a load of things to keep your house safe with and defend yourself from attackers.''' #mandatory
	displayURL="https://discord.gg/U8DvBAW"
	credits="Thanks to all of you guys for your support!"
	authors="Geforce132, bl4ckscor3, Redstone_Dubstep"

[[dependencies.securitycraft]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.securitycraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.18)"
    ordering="NONE"
    side="BOTH"