modLoader="javafml"
loaderVersion="${loader_version_range}"
logoFile="sc_banner.png"
license="GNU GPL v3.0 https://github.com/Geforce132/SecurityCraft/blob/${git_branch}/LICENSE"
issueTrackerURL="http://github.com/Geforce132/SecurityCraft/issues"

[[mods]]
	modId="securitycraft"
	version="${mod_version}"
	displayName="SecurityCraft"
	updateJSONURL="https://www.github.com/Geforce132/SecurityCraft/raw/master/Updates/Forge.json"
	description='''Adds a load of things to keep your house safe with and defend yourself from attackers.'''
	displayURL="https://discord.gg/U8DvBAW"
	credits="Thanks to all of you guys for your support!"
	authors="Geforce132, bl4ckscor3, Redstone_Dubstep"

[[dependencies.securitycraft]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.securitycraft]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[modproperties.securitycraft]
    catalogueImageIcon="sc_logo.png"