blank_issues_enabled: false
contact_links:
  - name: SecurityCraft Discord (for example to post suggestions or get help)
    url: https://discord.gg/U8DvBAW
    about: The best place to receive quick answers to any questions, post feature requests, and anything else you may have.